In [ ]:
import os
# import Google Drive 套件
from google.colab import drive
# 將自己的雲端硬碟掛載上去
drive.mount('/content/gdrive')

os.chdir('./gdrive/MyDrive/Colab Notebooks/cheng_ta/hw1')      # 檔案目錄

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
#shutil.rmtree('./train_data')

In [ ]:
import shutil
copyPath = './gdrive/MyDrive/Colab Notebooks/cheng_ta/hw1/train_data'
pastePath = './train_data'
shutil.copytree(copyPath, pastePath)

In [ ]:
import importlib
import random
import pickle
import logging
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import os
import time
import fun_cls as fc
import DrBC_modle as Dm
import networkx as nx
import networkx.algorithms.centrality as GC

# train data generative

In [ ]:
import networkx as nx
import networkx.algorithms.centrality as GC

# G = nx.generators.random_graphs.powerlaw_cluster_graph(5000, 4, 0.05)  生成圖
# G.nodes
# G.edges
# BC_dict = GC.betweenness_centrality(G)  計算 Betweenness

In [ ]:
n = 10

In [ ]:
for i in range(1, n+1):
    G = nx.generators.random_graphs.powerlaw_cluster_graph(150, 4, 0.05)
    d = GC.betweenness_centrality(G)

    nx.write_edgelist(G, "./test_data/syn_data/10000/orign/test_edge10000_{}".format(i))
    with open("./test_data/syn_data/10000/orign/test_betweenness10000_{}".format(i).format(i), 'wb') as f:
        pickle.dump(d, f)

    myG = fc.myGraph()
    myG.nodeProcess(G=G)
    myG.scoreProcess(G_dict=d)
    myG.degree_Coeffient()
    
    with open('./test_data/syn_data/10000/test_G{}'.format(i), 'wb') as f:
        pickle.dump(myG, f)

    del(G)
    del(d)
    del(myG)

# test Data Process

# youtube data

In [1]:
importlib.reload(fc)

NameError: ignored

In [ ]:
G = fc.myGraph()
G.nodeProcess('./hw1_data/youtube/com-youtube.txt')
G.scoreProcess('./hw1_data/youtube/com-youtube_score.txt')
len(G.scoreList)

1134890

In [ ]:
G.degree_Coeffient()

In [ ]:
with open('./test_data/youdata.pickle', 'wb') as f:
    pickle.dump(G, f)

In [ ]:
with open('./test_data/youdata.pickle', 'rb') as f:
    G = pickle.load(f)

In [ ]:
n = 200
path = './test_data/you_data/'

In [ ]:
# for i in range(1, n+1):
#   G_sub = G.sub_graph(N=10000, r=True)
#   G_sub.degree_Coeffient()
#   with open(path + 'subgraph{}.pickle'.format(str(i)), 'wb') as f:
#     pickle.dump(G_sub, f)

# synthetic

In [ ]:
importlib.reload(fc)

<module 'fun_cls' from 'D:\\study\\成大\\soa2\\cheng_te\\hw1\\fun_cls.py'>

In [ ]:
path = './hw1_data/Synthetic/10000/'
for i in range(30):
    vectors = '{}.txt'.format(str(i))
    scores = '{}_score.txt'.format(str(i))
    G = fc.myGraph()
    G.nodeProcess(files=path + vectors, splitx='\t')
    G.scoreProcess(files=path + scores)
    G.degree_Coeffient()
    with open('./test_data/syn_data/10000/syn{}.pickle'.format(str(i)), 'wb') as f:
        pickle.dump(G, f)


In [ ]:
path = './hw1_data/Synthetic/50000/'
for i in range(30):
    vectors = '{}.txt'.format(str(i))
    scores = '{}_score.txt'.format(str(i))
    G = fc.myGraph()
    G.nodeProcess(files=path + vectors, splitx='\t')
    G.scoreProcess(files=path + scores)
    G.degree_Coeffient()
    with open('./test_data/syn_data/20000/syn{}.pickle'.format(str(i)), 'wb') as f:
        pickle.dump(G, f)

In [ ]:
os.getcwd()

'/content/gdrive/My Drive/Colab Notebooks/cheng_ta/hw1'

# try

In [ ]:
files

['0.txt',
 '0_score.txt',
 '1.txt',
 '10.txt',
 '10_score.txt',
 '11.txt',
 '11_score.txt',
 '12.txt',
 '12_score.txt',
 '13.txt',
 '13_score.txt',
 '14.txt',
 '14_score.txt',
 '15.txt',
 '15_score.txt',
 '16.txt',
 '16_score.txt',
 '17.txt',
 '17_score.txt',
 '18.txt',
 '18_score.txt',
 '19.txt',
 '19_score.txt',
 '1_score.txt',
 '2.txt',
 '20.txt',
 '20_score.txt',
 '21.txt',
 '21_score.txt',
 '22.txt',
 '22_score.txt',
 '23.txt',
 '23_score.txt',
 '24.txt',
 '24_score.txt',
 '25.txt',
 '25_score.txt',
 '26.txt',
 '26_score.txt',
 '27.txt',
 '27_score.txt',
 '28.txt',
 '28_score.txt',
 '29.txt',
 '29_score.txt',
 '2_score.txt',
 '3.txt',
 '3_score.txt',
 '4.txt',
 '4_score.txt',
 '5.txt',
 '5_score.txt',
 '6.txt',
 '6_score.txt',
 '7.txt',
 '7_score.txt',
 '8.txt',
 '8_score.txt',
 '9.txt',
 '9_score.txt']

In [ ]:
t = torch.zeros(5, dtype=torch.float)

In [ ]:
t[1] = 5

In [ ]:
t

tensor([0., 5., 0., 0., 0.])

In [ ]:
t.dtype

torch.float32

In [ ]:
x = torch.zeros(5, 2, dtype=torch.float)
y = torch.zeros(3, 2, dtype=torch.float)

In [ ]:
torch.cat([x, y], dim=0).dtype

torch.float32

In [ ]:
torch.tensor((2, 1, 1), dtype=torch.float)

tensor([2., 1., 1.])

In [ ]:
x = torch.ones(3, 5)
y = torch.rand(1, 5)

In [ ]:
x[1:2, :].mm(y.T)

tensor([[2.0500]])

In [ ]:
x

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
datas = []
files = os.listdir('./train_data/')

In [ ]:
for i in files:
    with open('./train_data/' + i, 'rb') as f:
        data = pickle.load(f)
        datas.append(data)

In [ ]:
datas[0]

In [ ]:
x = torch.rand(6, 5)

In [ ]:
x

tensor([[0.8843, 0.7773, 0.1715, 0.9839, 0.2829],
        [0.1524, 0.2409, 0.2110, 0.0722, 0.1951],
        [0.7624, 0.1617, 0.3704, 0.0412, 0.5646],
        [0.8371, 0.0538, 0.8471, 0.6656, 0.3353],
        [0.4656, 0.5618, 0.2688, 0.6687, 0.7044],
        [0.9570, 0.9316, 0.7611, 0.2741, 0.5645]])

In [ ]:
y = x.view([1, 6, 5])
z = torch.cat([y, y+1])

In [ ]:
z.max(dim=0)[0]

tensor([[1.8843, 1.7773, 1.1715, 1.9839, 1.2829],
        [1.1524, 1.2409, 1.2110, 1.0722, 1.1951],
        [1.7624, 1.1617, 1.3704, 1.0412, 1.5646],
        [1.8371, 1.0538, 1.8471, 1.6656, 1.3353],
        [1.4656, 1.5618, 1.2688, 1.6687, 1.7044],
        [1.9570, 1.9316, 1.7611, 1.2741, 1.5645]])

In [ ]:
x = torch.ones((2, 2), dtype=torch.float)
y = torch.zeros(2, dtype=torch.float)

In [ ]:
y.view([1, 2]).mm(x)

tensor([[0., 0.]])